In [17]:
import test
import numpy as np

In [5]:
a = test.Array()

In [7]:
a = [[2, 3],[4, 5]]

In [8]:
a

[[2, 3], [4, 5]]

In [9]:
test.print_array(a)

In [10]:
b = test.Line()

In [12]:
b = [1, 2, 3, 5, 6]

In [15]:
type(a)

list

In [16]:
a

[[2, 3], [4, 5]]

In [18]:
b = np.asarray(b) 

In [20]:
a = np.asarray(a)

In [21]:
a

array([[2, 3],
       [4, 5]])

In [22]:
b

array([1, 2, 3, 5, 6])

In [43]:
c = test.Array()

In [57]:
c = [[[0, 0, 0],[1, 1, 1],[2, 2, 2],],[[3, 3, 3],[4, 4, 4],[5, 5, 5]],[[6, 6, 6],[7, 7, 7],[8, 8, 8]]]

In [58]:
c

[[[0, 0, 0], [1, 1, 1], [2, 2, 2]],
 [[3, 3, 3], [4, 4, 4], [5, 5, 5]],
 [[6, 6, 6], [7, 7, 7], [8, 8, 8]]]

In [59]:
c

[[[0, 0, 0], [1, 1, 1], [2, 2, 2]],
 [[3, 3, 3], [4, 4, 4], [5, 5, 5]],
 [[6, 6, 6], [7, 7, 7], [8, 8, 8]]]

In [61]:
c = np.asarray(c)

In [62]:
c

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]],

       [[6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]]])

In [56]:
for item in c:
    for in_item in item:
        print(in_item)

123
[[125, [[75, 65, 159], [0, 0, 0]]], [1, 2, 3]]
[5, 5, [7, 8, 9]]
[5, 7]
[0, 89]
[4, 5, 6]
